------KHACHHANG
--KIEMTRA
IF OBJECT_ID('KHACHHANG') IS NOT NULL
DROP TABLE KHACHHANG 
GO
CREATE TABLE KHACHHANG
(
 MAKH NVARCHAR(10) NOT NULL,
 HOTEN NVARCHAR(50) NULL,
 DIACHI NVARCHAR(100) NULL,
 EMAIL NVARCHAR(100) NULL,
 DIENTHOAI NVARCHAR(50)NULL,
 --KHOA CHINH
 CONSTRAINT PK_KHACHHANG PRIMARY KEY(MAKH)
)

------SANPHAM
--KIEMTRA
IF OBJECT_ID('SANPHAM') IS NOT NULL
DROP TABLE SANPHAM
GO
CREATE TABLE SANPHAM
(
 MASP NVARCHAR(10) NOT NULL,
 MOTA NVARCHAR(50) NULL,
 GIA MONEY,
 TENSANPHAM NVARCHAR(20)NULL,
 --KHOA CHINH
 CONSTRAINT PK_SANPHAM PRIMARY KEY(MASP)
)

------HOADON
--KIEMTRA
IF OBJECT_ID('HOADON') IS NOT NULL
DROP TABLE HOADON
GO
CREATE TABLE HOADON
(
 MAHD NVARCHAR(10) NOT NULL,
 NGAYMUA DATE,
 MAKH NVARCHAR(10),
 TRANGTHAI NVARCHAR(50),
 --KHOA CHINH
 CONSTRAINT PK_HOADON PRIMARY KEY(MAHD),
 CONSTRAINT FK_KHACHHANG_HOADON FOREIGN KEY (MAKH) REFERENCES KHACHHANG
)


------HOADONCHITIET
--KIEMTRA
IF OBJECT_ID('HOADONCT') IS NOT NULL
DROP TABLE HOADONCT
GO
CREATE TABLE HOADONCT
(
 MAHD NVARCHAR(10) NOT NULL,
 MASP NVARCHAR (10) NOT NULL,
 SOLUONGBAN INT,
 TRANGTHAI NVARCHAR(50),
 CONSTRAINT FK_HOADONCT_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON,
 CONSTRAINT FK_HOADONCT_SANPHAM FOREIGN KEY (MASP) REFERENCES SANPHAM,
 CONSTRAINT PK_HOADONCT PRIMARY KEY (MASP,MAHD),
)
--NHẬP DỮ LIỆU VÀO BẢNG
DELETE FROM kHACHHANG
INSERT INTO KHACHHANG(MAKH,HOTEN,DIACHI,EMAIL,DIENTHOAI) VALUES (N'PH01',N'NGUYỄN THU THẢO',N'PHÚ MINH-PHÚC LÝ-MINH KHAI-BẮC TỪ LIÊM-HÀ NỘI',N'THAONTPH06790@FPT.EDU.VN','01673502523')
INSERT INTO SANPHAM(MASP,TENSANPHAM,MOTA,GIA) VALUES (N'01',N'BÀN LÀM VIỆC',N'RỘNG 1M2-MÀU XÁM-GỖ',1050000)
INSERT INTO HOADON(MAHD,MAKH,NGAYMUA,TRANGTHAI) VALUES (N'HD01',N'PH01',N'2018-09-29',N'ĐÃ THANH TOÁN')
INSERT INTO HOADONCT()
SELECT * FROM KHACHHANG
SELECT * FROM SANPHAM